<a href="https://colab.research.google.com/github/Karsuman4298/AI_project/blob/main/PYtorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
tensor= torch.tensor([[5,7],
                       [6,6],
                           ])

In [3]:
tensor

tensor([[5, 7],
        [6, 6]])

In [4]:
tensor.shape

torch.Size([2, 2])

In [5]:
tensor.ndim

2

random tensors

In [6]:
random_tensors= torch.rand(3,2)
print(random_tensors)

tensor([[0.8116, 0.1895],
        [0.8156, 0.4680],
        [0.3935, 0.2287]])


In [7]:
random_tensors.ndim

2

  Random tensors to size of an image

In [8]:
rand_tensor_img= torch.rand(size=(224,224,3))

rand_tensor_img.shape, rand_tensor_img.ndim

(torch.Size([224, 224, 3]), 3)

In [9]:
range=torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
ten_zeros=torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
print("hiii")

hiii


In [17]:
float_32_tensor= torch.tensor([2.0,3.0,4.0,5.0],dtype=None,device=
                              'cuda',requires_grad=False)

In [19]:
float_32_tensor.dtype
float_32_tensor.device

device(type='cuda', index=0)

In [20]:
float_16_tensor= float_32_tensor.type(torch.float)

In [21]:
float_16_tensor.dtype

torch.float32